name: KVReplicator CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kvreplicator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Checkout the code into the GITHUB_WORKSPACE/kvreplicator directory
          # to match the local structure and simplify paths.
          path: kvreplicator

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "kvreplicator/go.mod" # Path to your go.mod file

      - name: Install RocksDB system library
        run: |
          sudo apt-get update
          sudo apt-get install -y librocksdb-dev build-essential
      - name: Install Go dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
