name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run GoSec security scanner
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          $(go env GOPATH)/bin/gosec ./...

      - name: Run govulncheck vulnerability scanner
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          $(go env GOPATH)/bin/govulncheck ./...

      - name: Run CodeQL security scanner
        uses: github/codeql-action@v2
        with:
          languages: go
          queries: security-and-quality
